version: '3'

services:

  # Elasticsearch Service
  elastic8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: ${PROJECT_NAME}_elastic8
    tty: true
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - type: volume
        source: elastic8
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - node.name=elastic8
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - indices.id_field_data.enabled=true
      - http.cors.enabled=true 
      - http.cors.allow-origin=/https:\/\/app.elasticvue.com/
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${PROJECT_NAME}_rabbitmq
    restart: unless-stopped
    tty: true
    ports:
      - "15672:15672"
    networks:
      - app-network

      # Redis Service
  redis:
    image: redis:5-alpine
    container_name: ${PROJECT_NAME}_redis
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  # Mail Service
  mailer:
    image: schickling/mailcatcher
    container_name: ${PROJECT_NAME}_mailer
    restart: unless-stopped
    tty: true
    ports:
      - "1080:1080"
    networks:
      - app-network

  # PHP 8.2 Service
  php82:
    image: petar1v/php82:latest
    container_name: ${PROJECT_NAME}_php82
    restart: unless-stopped
    tty: true
    user: "1000:1000"
    environment:
      SERVICE_NAME: php82
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network


  # PHP 8.1 Service
  php81:
    image: petar1v/php81:latest
    container_name: ${PROJECT_NAME}_php81
    restart: unless-stopped
    tty: true
    user: "1000:1000"
    environment:
      SERVICE_NAME: php81
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # PHP 7.2 Service
  php72:
    image: petar1v/php72:latest
    container_name: ${PROJECT_NAME}_php72
    restart: unless-stopped
    tty: true
    user: "1000:1000"
    command: ["php-fpm"]
    environment:
      SERVICE_NAME: php72
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network


  # NGINX Service
  web:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_web
    restart: unless-stopped
    tty: true
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - app-network

  # Composer service
  composer:
    image: composer:latest
    container_name: ${PROJECT_NAME}_composer
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    user: "1000:1000"
    command: ["composer"]
    networks:
      - app-network

  # MYSQL 8.0 Service
  mysql8:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql8
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: mysql8
        target: /var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network

  # MYSQL 5.7 Service
  mysql5:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}__mysql5
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: mysql5
        target: /var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33061:3306"
    networks:
      - app-network

  # Uptime-Kuma Service
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: ${PROJECT_NAME}_uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - app-network


# DOCKER Volumes
volumes:
  mysql8:
    driver: local
  mysql5:
    driver: local
  elastic8:
    driver: local
  uptime-kuma-data:
    driver: local

# DOCKER Networks
networks:
  app-network:
    name: ${PROJECT_NAME}-network
    driver: bridge
