include /var/www/nuzu/nginx.conf;
include /var/www/NewsSite/nginx.conf;
include /var/www/Repairs/nginx.conf;
include /var/www/laravel/nginx.conf;
include /var/www/Ardes2.0/nginx.conf;
include /var/www/pixabay/nginx.conf;
include /var/www/pixabay-recreation/nginx.conf;
include /var/www/l37sg0.com/nginx.conf;
#include /var/www/beshared/nginx.conf;
#include /var/www/prestashop/nginx.conf;
#include /var/www/gamento/nginx.conf;
include /var/www/crafty-creations/nginx.conf;
include /var/www/rocketCV/nginx.conf;
include /var/www/symfony-guestbook/nginx.conf;
include /var/www/symfony-guestbook/spa/nginx.conf;
include /var/www/mehana-lian/nginx.conf;

server {
  listen 80;

  server_name mail.localhost;

  location / {
    proxy_pass http://mailer:1080;
  }

}
